# Generated by Django 3.2.2 on 2021-05-22 19:13

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('todoapp', '0003_remove_project_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='users',
            field=models.ManyToManyField(default=1, related_name='users', to=settings.AUTH_USER_MODEL),
        ),
    ]
