# Generated by Django 3.2.2 on 2021-05-22 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0003_remove_project_user'),
        ('usersapp', '0002_customuser_project'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='project',
        ),
        migrations.AddField(
            model_name='customuser',
            name='project',
            field=models.ManyToManyField(default=1, related_name='users', to='todoapp.Project'),
        ),
    ]
