# Generated by Django 3.2.2 on 2021-05-22 19:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usersapp', '0003_auto_20210522_2159'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='project',
        ),
    ]
